default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: haslo

development:
  <<: *default
  database: epic_gallery_development

test:
  <<: *default
  database: epic_gallery_test

production:
  <<: *default
  database: epic_gallery_production
  username: epic_gallery
  password: <%= ENV['EPIC_GALLERY_DATABASE_PASSWORD'] %>
